name: Run tistory auto posting bot
on:
  schedule:
         - cron: "0 22 * * *"      
  push:
    branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.x
              uses: actions/setup-python@v1
              with:
                  python-version: "3.9"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Python Script
              run: |
                  python "program.py"
              env: # Or as an environment variable
                  TISTORY_ACCESS_TOKEN: ${{ secrets.TISTORY_ACCESS_TOKEN }}
                  OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
                  UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
